create table app_user
(
    id              bigint generated by default as identity primary key,
    email           text      not null unique,
    password        text      not null,
    first_name      text      not null,
    last_name       text      not null,
    created_at      timestamp not null default current_timestamp,
    created_by      text      not null,
    last_updated_at timestamp,
    last_updated_by text,
    version         int       not null default 0
);

INSERT INTO public.app_user (email, password, first_name, last_name, created_by)
VALUES ('admin@pethub.com', '{bcrypt}$2a$10$WO9MllE2D9Jq9xgWBdJW6u569K5Eux8Y.VOaXNxHDykYdsqYCXcpC', 'Admin', 'Admin', 'system'),
       ('user@pethub.com', '{bcrypt}$2a$10$WEs.Ad8P7WbzGuzgJmnciO65vTuVaUjIaupC7eeMb1qtvnG7ShGkS', 'User', 'User', 'system');
