create table app_role
(
    id   int generated by default as identity primary key,
    name text not null
);

insert into app_role (id, name)
values (1, 'admin'),
       (2, 'user');

create table user_role
(
    user_id bigint not null references app_user (id) on delete cascade,
    role_id int    not null references app_role (id) on delete restrict,

    primary key (user_id, role_id)
);

insert into user_role (user_id, role_id)
values (1, 1),
       (1, 2),
       (2, 2);
