create table weather_station
(
    id              bigint generated by default as identity primary key,
    external_id     varchar(255) not null unique,
    name            varchar(255) not null,
    timezone        varchar(255),
    latitude        decimal(3, 2),
    longitude       decimal(3, 2),
    elevation       decimal(5, 2),
    country_code    varchar(2)   not null references country (alpha_2_code),
    created_at      timestamp    not null default current_timestamp,
    created_by      text         not null,
    last_updated_at timestamp,
    last_updated_by text,
    version         int          not null default 0
)
