create table weather_station_import_status
(
    id   int primary key,
    name varchar(255) not null
);

insert into weather_station_import_status(id, name)
values (1, 'REQUESTED'),
       (2, 'STARTED'),
       (3, 'IN_PROGRESS'),
       (4, 'COMPLETED'),
       (5, 'FAILED');

create table weather_station_import
(
    id                 bigint generated by default as identity primary key,
    file_hash          int          not null unique,
    requested_at       timestamp,
    requested_by       varchar(255) not null,
    is_manual_import   boolean      not null,
    started_at         timestamp,
    finished_at        timestamp,
    status_description varchar(1000),
    import_status_id   int          not null references weather_station_import_status (id)
);

create table weather_station
(
    id              bigint generated by default as identity primary key,
    external_id     varchar(255) not null unique,
    name            varchar(255) not null,
    timezone        varchar(255),
    latitude        decimal(3, 2),
    longitude       decimal(3, 2),
    elevation       decimal(5, 2),
    country_code    varchar(2)   not null references country (alpha_2_code),
    import_id       bigint       not null references weather_station_import (id),
    created_at      timestamp    not null default current_timestamp,
    created_by      text         not null,
    last_updated_at timestamp,
    last_updated_by text,
    version         int          not null default 0
);
