# provided health checks (even though Spring Boot does its own) in favor of starting containers manually (and to have pre-condition)
name: pet-hub
services:
    postgres:
        image: 'postgres:16.3-alpine'
        container_name: 'pet-postgres'
        environment:
            - 'POSTGRES_DB=pet_hub'
            - 'POSTGRES_PASSWORD=pet-password'
            - 'POSTGRES_USER=pet-admin'
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d postgres -U pet-admin" ]
            interval: 10s
            timeout: 5s
            retries: 3

    rabbitmq:
        container_name: 'pet-rabbitmq'
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 3s
            retries: 3

    mongodb:
        image: 'mongo:8.0-rc-noble'
        container_name: 'pet-mongodb'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'pet-admin'
            MONGO_INITDB_ROOT_PASSWORD: 'pet-password'
            MONGO_INITDB_DATABASE: 'petHub'
        ports:
            - '27017:27017'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
