# provided health checks (even though Spring Boot does its own) in favor of starting containers manually (and to have pre-condition)
services:
    postgres:
        image: 'postgres:16.3-alpine'
        container_name: 'pet-postgres'
        environment:
            - 'POSTGRES_DB=pet_hub'
            - 'POSTGRES_PASSWORD=pet-password'
            - 'POSTGRES_USER=pet-admin'
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d postgres -U pet-admin" ]
            interval: 10s
            timeout: 5s
            retries: 3
    rabbitmq:
        container_name: 'pet-rabbitmq'
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 3s
            retries: 3
